#!/usr/bin/env python3
import os
import sys
import subprocess
import re

def check_root():
    """Dmiddecode requires root privileges to read raw system memory tables."""
    if os.geteuid() != 0:
        print("[-] Error: Root privileges required to read motherboard SMBIOS tables.")
        print("    Please execute using: sudo python3 ram_check.py")
        sys.exit(1)

def get_motherboard_info():
    """Queries Type 2 SMBIOS tables to extract explicit Motherboard Manufacturer and Model data."""
    mobo = {"manufacturer": "Unknown Manufacturer", "model": "Unknown Model"}
    try:
        raw_output = subprocess.check_output(["dmidecode", "-t", "2"], text=True)
        for line in raw_output.split('\n'):
            line = line.strip()
            if "Manufacturer:" in line:
                mobo["manufacturer"] = line.split(":", 1)[1].strip()
            elif "Product Name:" in line:
                mobo["model"] = line.split(":", 1)[1].strip()
    except Exception:
        pass
    return mobo

def parse_memory_slots():
    try:
        # Pull Type 17 data structures (Memory Device details)
        raw_output = subprocess.check_output(["dmidecode", "-t", "17"], text=True)
    except FileNotFoundError:
        print("[-] Error: 'dmidecode' utility is missing from this system.")
        print("    Install it using your package manager (e.g., sudo apt install dmidecode).")
        sys.exit(1)
    except subprocess.CalledProcessError as e:
        print(f"[-] Error querying hardware tables: {e}")
        sys.exit(1)

    # Split output into blocks representing individual slots
    device_blocks = raw_output.split("Memory Device")
    parsed_slots = []

    for block in device_blocks[1:]:
        lines = block.split('\n')
        slot_info = {
            "locator": "Unknown Slot",
            "size": "No Module Installed",
            "speed": "Unknown",
            "type": "Unknown",
            "ram_manufacturer": "N/A",
            "ram_model": "N/A",
            "active": False
        }
        
        for line in lines:
            line = line.strip()
            if "Locator:" in line and "Bank Locator:" not in line:
                slot_info["locator"] = line.split(":", 1)[1].strip()
            elif "Size:" in line:
                size_value = line.split(":", 1)[1].strip()
                slot_info["size"] = size_value
                if "No Module" not in size_value and "Unknown" not in size_value:
                    slot_info["active"] = True
            elif "Speed:" in line and "Configured" not in line:
                slot_info["speed"] = line.split(":", 1)[1].strip()
            elif "Type:" in line and "Detail" not in line:
                slot_info["type"] = line.split(":", 1)[1].strip()
            elif "Manufacturer:" in line:
                slot_info["ram_manufacturer"] = line.split(":", 1)[1].strip()
            elif "Part Number:" in line:
                slot_info["ram_model"] = line.split(":", 1)[1].strip()

        # Clean up fallback placeholder strings generated by unpopulated slots or generic firmware
        if not slot_info["active"]:
            slot_info["ram_manufacturer"] = "N/A"
            slot_info["ram_model"] = "N/A"
        else:
            bad_strings = ["Not Specified", "Unknown", "0000", "0x0000"]
            if any(x in slot_info["ram_manufacturer"] for x in bad_strings):
                slot_info["ram_manufacturer"] = "Unknown"
            if any(x in slot_info["ram_model"] for x in bad_strings):
                slot_info["ram_model"] = "Unknown"

        parsed_slots.append(slot_info)
    
    return parsed_slots

def compile_diagnostic_file(mobo, slots, target_file="ram_diagnostic_report.txt"):
    total_slots = len(slots)
    active_slots = [s for s in slots if s["active"]]
    inactive_slots = [s for s in slots if not s["active"]]
    
    # Calculate total hardware capacity directly from functional modules
    total_hardware_gb = 0
    for s in active_slots:
        size_match = re.search(r'(\d+)\s*(GB|MB)', s["size"], re.IGNORECASE)
        if size_match:
            value = int(size_match.group(1))
            unit = size_match.group(2).upper()
            total_hardware_gb += value if unit == "GB" else (value / 1024)

    # Scale document boundary line to handle the new detailed columns
    report_width = 96

    with open(target_file, "w", encoding="utf-8") as f:
        f.write("=" * report_width + "\n")
        f.write("                       MOTHERBOARD RAM DIAGNOSTIC REPORT\n")
        f.write("=" * report_width + "\n\n")
        
        # Motherboard Info & Metrics Summary Section (Placed explicitly at the top)
        f.write("--- HARDWARE IDENTIFICATION SUMMARY ---\n")
        f.write(f"Motherboard Manufacturer:          {mobo['manufacturer']}\n")
        f.write(f"Motherboard Make/Model:            {mobo['model']}\n")
        f.write(f"Total Physical Motherboard Slots:   {total_slots}\n")
        f.write(f"Active Slots (Module Detected):     {len(active_slots)}\n")
        f.write(f"Inactive Slots (Empty or Offline):  {len(inactive_slots)}\n")
        f.write(f"Sum Total Sized from Modules:       {total_hardware_gb:.2f} GB\n\n")
        
        if total_hardware_gb <= 8 and len(active_slots) == total_slots and total_slots > 1:
            f.write("([!]) WARNING SUMMARY DETECTED:\n")
            f.write(f"    System reports all {total_slots} physical slots are populated, but only {total_hardware_gb:.1f} GB total is recognized.\n")
            f.write("    - Verify if individual modules show abnormally low capacity readings below.\n")
            f.write("    - If specific slots are missing entirely from the topology map, check for channel training\n")
            f.write("      faults, unseated sticks, or a mismatch in dual-rank compatibility settings.\n\n")

        # Graphical Topology Map Section
        f.write("--- GRAPHICAL TOPOLOGY MAP ---\n")
        f.write("Proximity Layout [CPU Socket / Memory Channels]\n")
        f.write("┌" + "─" * (report_width - 2) + "┐\n")
        
        for idx, s in enumerate(slots, start=1):
            status_bracket = "[  ONLINE  ]" if s["active"] else "[ OFFLINE  ]"
            bar_texture = "████████████" if s["active"] else "░░░░░░░░░░░░"
            
            locator_str = f"Slot {idx:02d} ({s['locator'][:12]})"
            # Adjusted padding layout boundaries
            f.write(f"│  {locator_str:<22} {bar_texture}    {s['size']:<22} {status_bracket:<14}  │\n")
            
        f.write("└" + "─" * (report_width - 2) + "┘\n\n")
        
        # Expanded Reconnaissance Log incorporating RAM Manufacturer and Part Model
        f.write("--- DETAILED RECONNAISSANCE LOG ---\n")
        f.write(f"{'Slot Locator':<16} | {'State':<8} | {'Capacity':<12} | {'Speed/Type':<16} | {'RAM Vendor':<14} | {'Part / Model'}\n")
        f.write("-" * report_width + "\n")
        for s in slots:
            state_label = "ACTIVE" if s["active"] else "INACTIVE"
            spec_label = f"{s['speed']} {s['type']}" if s["active"] else "N/A"
            # Truncate strings gracefully if vendor headers or part numbers overflow column buffers
            vendor_str = s['ram_manufacturer'][:14]
            model_str = s['ram_model'][:20]
            
            f.write(f"{s['locator']:<16} | {state_label:<8} | {s['size']:<12} | {spec_label:<16} | {vendor_str:<14} | {model_str}\n")
            
        f.write("\n" + "=" * report_width + "\n")
        f.write("End of low-level diagnostic report.\n")
        
    print(f"[+] Execution completed successfully.")
    print(f"[+] Motherboard: {mobo['manufacturer']} -> {mobo['model']}")
    print(f"[+] Total Slots Mapped: {total_slots}")
    print(f"[+] Output compiled to: {os.path.abspath(target_file)}")

if __name__ == "__main__":
    check_root()
    motherboard = get_motherboard_info()
    detected_slots = parse_memory_slots()
    compile_diagnostic_file(motherboard, detected_slots)